language:
    - julia

julia:
    - 1.3

addons:
  apt:
    packages:
      - python3-pip

before_install:
    - pip3 install --user uproot
    - git clone git@github.com:mppmu/gerda-gems-sw.git
    - julia -e 'using Pkg; Pkg.add(readlines("gerda-gems-sw/src/GeMS.jl/REQUIRE"))'
    - export JULIA_LOAD_PATH="$JULIA_LOAD_PATH:`pwd`/gerda-gems-sw/src/GeMS.jl"

install: true

script:
    - julia -e "using GeMS; GeMS.run_db_tests(\"phaseIIplus\")"
